import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateAllTimestampsToTimestamptz1787636319625 implements MigrationInterface {
    name = 'UpdateAllTimestampsToTimestamptz1787636319625'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_branches_tenant"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_customers_tenant"`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP CONSTRAINT "FK_attributes_tenant"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP CONSTRAINT "FK_attribute_values_attribute"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_categories_tenant"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_product_images_tenant"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_tenant"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_category"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP CONSTRAINT "FK_product_stocks_branch"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP CONSTRAINT "FK_product_stocks_variant"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_tags_tenant"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_product_variants_product"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_product_variants_tenant"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_inventory_movements_tenant"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_inventory_movements_origin"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_inventory_movements_destination"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_inventory_movements_variant"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_inventory_movements_purchase_order"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_suppliers_tenant"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_purchase_order_items_purchase_order"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_purchase_order_items_variant"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_purchase_orders_tenant"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_purchase_orders_supplier"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_purchase_orders_branch"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_product_batches_tenant"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_product_batches_branch"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_product_batches_variant"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_product_batches_purchase_order"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_tenant"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_cash_sessions_branch"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_cash_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_expenses_tenant"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_expenses_branch"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_expenses_cash_session"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_sale_items_sale"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_sale_items_variant"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_sale_payments_sale"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_tenant"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_branch"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_cash_session"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_customer"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_sales_user_id"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_refunds_tenant"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_refunds_branch"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_refunds_sale"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_refunds_cash_session"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_refunds_user_id"`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP CONSTRAINT "FK_refund_items_refund"`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP CONSTRAINT "FK_refund_items_variant"`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" DROP CONSTRAINT "FK_product_image_mappings_product"`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" DROP CONSTRAINT "FK_product_image_mappings_image"`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" DROP CONSTRAINT "FK_variant_attribute_values_variant"`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" DROP CONSTRAINT "FK_variant_attribute_values_value"`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" DROP CONSTRAINT "FK_product_variant_image_mappings_variant"`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" DROP CONSTRAINT "FK_product_variant_image_mappings_image"`);
        await queryRunner.query(`ALTER TABLE "variant_tags" DROP CONSTRAINT "FK_variant_tags_variant"`);
        await queryRunner.query(`ALTER TABLE "variant_tags" DROP CONSTRAINT "FK_variant_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_tenants_ruc_partial"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_customers_tenant_identity"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_product_variants_tenant_sku"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_product_variants_tenant_barcode"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_suppliers_tenant_identity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_batches_branch_variant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_product_batches_remaining_qty"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_users_email_partial"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP CONSTRAINT "UQ_product_stocks_branch_variant"`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "UQ_3d357209e328784b938a13a0a8a" UNIQUE ("ruc")`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "total_amount" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d851ed7b267740601149d6a6bf" ON "customers"  ("tenant_id", "identity_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5cc5222a2b5189e03a9a15bfb9" ON "product_stocks"  ("branch_id", "variant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_039284cb29b197891c2f9819fc" ON "product_batches"  ("branch_id", "variant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4f2f24f40637b7a05430cb1a9" ON "product_image_mappings"  ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf12784f218533772a2a7858bf" ON "product_image_mappings"  ("product_image_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5df07e5f75117c9eca2c2ba505" ON "variant_attribute_values"  ("variant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c714239ff4355d5e4dbfed5d19" ON "variant_attribute_values"  ("attribute_value_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae9ab0696287a070f058b85ee3" ON "product_variant_image_mappings"  ("product_variant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_38169a46360df039c784df273d" ON "product_variant_image_mappings"  ("product_image_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_125c952140897f884c7194029f" ON "variant_tags"  ("variant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c0d2af701152c5649ba2cf4f6" ON "variant_tags"  ("tag_id") `);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_fda619979f40a6a44fc9baf02c3" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_97913f35ac2e435a4463fb50a01" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD CONSTRAINT "FK_8df16cd370327023ca61899161b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD CONSTRAINT "FK_be02d0f6a15bc7a0d835f832b62" FOREIGN KEY ("attribute_id") REFERENCES "attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_5d4fe23b360b1b9e16a3f41727f" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_866b999f190dfdec5a077e1abc5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9c365ebf78f0e8a6d9e4827ea70" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD CONSTRAINT "FK_b2a5c4ff5b3a8b01378a57a0339" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD CONSTRAINT "FK_face1769513c756a5fb296ad8db" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_4c9d89c0373bf1e54134eb21eac" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_553196ea54b383f352401962af2" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_08344cc99d67ce2b3bd27831e13" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_e774770eb44c0e4f399a86e4030" FOREIGN KEY ("origin_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_c6e08f66c969c22162d1162aa80" FOREIGN KEY ("destination_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_1bb851d7c7ef2435fad91cae453" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_b0d0350059126fa08fddc3c7a46" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_c7a528a540ba57bfc7bac43109b" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_237678c98436e0abb48b3060c82" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_4e8bac0190418631f7e2c3c6786" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_b9e08a98a3e2f0245ce3b6cf1d2" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_9e874589807ffcc252fb3b06fc7" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_011591d355c11e2082dce47f11e" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_11f61ce8c6dc0bfcbed082ef7d5" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_04ff8cefb5ce273f29487898ef9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_e86e6bebe054a040132d2aeb5bc" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_866a3b82ff438efc19c2398cda6" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_051d3c1315bc8d8b0567feff198" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c210a330b80232c29c2ad68462a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_8a27886f7a349f48572087f91da" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_ae6cc7812b56c7a03599a407d90" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_236f3154522de80a98f87c66b84" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_4e85abc6ca85052e6703762ec30" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_5f282f3656814ec9ca2675aef6f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_34fda442f4afcabe72988b5dc32" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_ce569fe42674bf5941d132966bf" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_5dcb85de1d184a6e1436dec41fd" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_899945d6a79857eb76ed38e21b8" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_3be163f822a41931bb73c243d82" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD CONSTRAINT "FK_79cde544708be9a0407c4b20bef" FOREIGN KEY ("refund_id") REFERENCES "refunds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD CONSTRAINT "FK_4b296d20e273a09c12a1fc94983" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" ADD CONSTRAINT "FK_d4f2f24f40637b7a05430cb1a9d" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" ADD CONSTRAINT "FK_cf12784f218533772a2a7858bf8" FOREIGN KEY ("product_image_id") REFERENCES "product_images"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" ADD CONSTRAINT "FK_5df07e5f75117c9eca2c2ba5051" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" ADD CONSTRAINT "FK_c714239ff4355d5e4dbfed5d196" FOREIGN KEY ("attribute_value_id") REFERENCES "attribute_values"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" ADD CONSTRAINT "FK_ae9ab0696287a070f058b85ee3c" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" ADD CONSTRAINT "FK_38169a46360df039c784df273da" FOREIGN KEY ("product_image_id") REFERENCES "product_images"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variant_tags" ADD CONSTRAINT "FK_125c952140897f884c7194029f4" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variant_tags" ADD CONSTRAINT "FK_3c0d2af701152c5649ba2cf4f60" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "variant_tags" DROP CONSTRAINT "FK_3c0d2af701152c5649ba2cf4f60"`);
        await queryRunner.query(`ALTER TABLE "variant_tags" DROP CONSTRAINT "FK_125c952140897f884c7194029f4"`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" DROP CONSTRAINT "FK_38169a46360df039c784df273da"`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" DROP CONSTRAINT "FK_ae9ab0696287a070f058b85ee3c"`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" DROP CONSTRAINT "FK_c714239ff4355d5e4dbfed5d196"`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" DROP CONSTRAINT "FK_5df07e5f75117c9eca2c2ba5051"`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" DROP CONSTRAINT "FK_cf12784f218533772a2a7858bf8"`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" DROP CONSTRAINT "FK_d4f2f24f40637b7a05430cb1a9d"`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP CONSTRAINT "FK_4b296d20e273a09c12a1fc94983"`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP CONSTRAINT "FK_79cde544708be9a0407c4b20bef"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_3be163f822a41931bb73c243d82"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_899945d6a79857eb76ed38e21b8"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_5dcb85de1d184a6e1436dec41fd"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_ce569fe42674bf5941d132966bf"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_34fda442f4afcabe72988b5dc32"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_5f282f3656814ec9ca2675aef6f"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_4e85abc6ca85052e6703762ec30"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_236f3154522de80a98f87c66b84"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_ae6cc7812b56c7a03599a407d90"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_8a27886f7a349f48572087f91da"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c210a330b80232c29c2ad68462a"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_051d3c1315bc8d8b0567feff198"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_866a3b82ff438efc19c2398cda6"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_e86e6bebe054a040132d2aeb5bc"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_04ff8cefb5ce273f29487898ef9"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_11f61ce8c6dc0bfcbed082ef7d5"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_011591d355c11e2082dce47f11e"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_9e874589807ffcc252fb3b06fc7"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_b9e08a98a3e2f0245ce3b6cf1d2"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP CONSTRAINT "FK_4e8bac0190418631f7e2c3c6786"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_237678c98436e0abb48b3060c82"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_c7a528a540ba57bfc7bac43109b"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_b0d0350059126fa08fddc3c7a46"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_1bb851d7c7ef2435fad91cae453"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_c6e08f66c969c22162d1162aa80"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_e774770eb44c0e4f399a86e4030"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_08344cc99d67ce2b3bd27831e13"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_553196ea54b383f352401962af2"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_4c9d89c0373bf1e54134eb21eac"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP CONSTRAINT "FK_face1769513c756a5fb296ad8db"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP CONSTRAINT "FK_b2a5c4ff5b3a8b01378a57a0339"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9c365ebf78f0e8a6d9e4827ea70"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_866b999f190dfdec5a077e1abc5"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_5d4fe23b360b1b9e16a3f41727f"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP CONSTRAINT "FK_be02d0f6a15bc7a0d835f832b62"`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP CONSTRAINT "FK_8df16cd370327023ca61899161b"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_97913f35ac2e435a4463fb50a01"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_fda619979f40a6a44fc9baf02c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c0d2af701152c5649ba2cf4f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_125c952140897f884c7194029f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38169a46360df039c784df273d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae9ab0696287a070f058b85ee3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c714239ff4355d5e4dbfed5d19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5df07e5f75117c9eca2c2ba505"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf12784f218533772a2a7858bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4f2f24f40637b7a05430cb1a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_039284cb29b197891c2f9819fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cc5222a2b5189e03a9a15bfb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d851ed7b267740601149d6a6bf"`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refund_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_batches" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "total_amount" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_stocks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "UQ_3d357209e328784b938a13a0a8a"`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD CONSTRAINT "UQ_product_stocks_branch_variant" UNIQUE ("branch_id", "variant_id")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_users_email_partial" ON "users" USING btree ("email") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_product_batches_remaining_qty" ON "product_batches" USING btree ("remaining_quantity") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_batches_branch_variant" ON "product_batches" USING btree ("branch_id", "variant_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_suppliers_tenant_identity" ON "suppliers" USING btree ("identity_number", "tenant_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_product_variants_tenant_barcode" ON "product_variants" USING btree ("barcode", "tenant_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_product_variants_tenant_sku" ON "product_variants" USING btree ("sku", "tenant_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_customers_tenant_identity" ON "customers" USING btree ("identity_number", "tenant_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_tenants_ruc_partial" ON "tenants" USING btree ("ruc") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`ALTER TABLE "variant_tags" ADD CONSTRAINT "FK_variant_tags_tag" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_tags" ADD CONSTRAINT "FK_variant_tags_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" ADD CONSTRAINT "FK_product_variant_image_mappings_image" FOREIGN KEY ("product_image_id") REFERENCES "product_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant_image_mappings" ADD CONSTRAINT "FK_product_variant_image_mappings_variant" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" ADD CONSTRAINT "FK_variant_attribute_values_value" FOREIGN KEY ("attribute_value_id") REFERENCES "attribute_values"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" ADD CONSTRAINT "FK_variant_attribute_values_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" ADD CONSTRAINT "FK_product_image_mappings_image" FOREIGN KEY ("product_image_id") REFERENCES "product_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image_mappings" ADD CONSTRAINT "FK_product_image_mappings_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD CONSTRAINT "FK_refund_items_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refund_items" ADD CONSTRAINT "FK_refund_items_refund" FOREIGN KEY ("refund_id") REFERENCES "refunds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_refunds_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_refunds_cash_session" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_refunds_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_refunds_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_refunds_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_cash_session" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_sales_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_sale_payments_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_sale_items_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_sale_items_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_expenses_cash_session" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_expenses_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_expenses_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_cash_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_cash_sessions_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_product_batches_purchase_order" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_product_batches_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_product_batches_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_batches" ADD CONSTRAINT "FK_product_batches_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_purchase_orders_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_purchase_orders_supplier" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_purchase_orders_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_purchase_order_items_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_purchase_order_items_purchase_order" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_suppliers_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_inventory_movements_purchase_order" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_inventory_movements_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_inventory_movements_destination" FOREIGN KEY ("destination_branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_inventory_movements_origin" FOREIGN KEY ("origin_branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_inventory_movements_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_product_variants_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_product_variants_product" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_tags_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD CONSTRAINT "FK_product_stocks_variant" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_stocks" ADD CONSTRAINT "FK_product_stocks_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_product_images_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_categories_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD CONSTRAINT "FK_attribute_values_attribute" FOREIGN KEY ("attribute_id") REFERENCES "attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD CONSTRAINT "FK_attributes_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_customers_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_branches_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
